name: Build and Deploy Multi-Container App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test client
        run: |
          echo -n '${{ secrets.DOCKER_PASSWORD }}'| docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t roeezach/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true roeezach/react-test npm test
        working-directory: ${{ github.workspace }}

      - name: Build and tag Docker images
        run: |
          docker build -t roeezach/multi-client ./client
          docker build -t roeezach/multi-worker ./worker
          docker build -t roeezach/multi-server ./server
        working-directory: ${{ github.workspace }}
